version: '3'

# Указываем версию Docker Compose, используемую для этого файла конфигурации.
services:
  # Определение сервиса API.
  api:
    restart: always # Настройка для автоматического перезапуска контейнера в случае его остановки.
    build: ./api # Указываем путь к директории с Dockerfile для сборки образа API-сервиса.
    ports:
      - "5555:5000" # Внешний порт 5555 будет сопоставлен с внутренним портом 5000 контейнера.

  # Определение сервиса фронтенд.
  frontend:
    restart: always # Перезапуск контейнера при остановке или сбое.
    build: ./frontend # Указанный путь к директории с Dockerfile для сборки образа.
    ports:
      - "8954:8954" # Подключение порта для доступа к фронтенд-сервису.

  # Определение сервиса базы данных MySQL.
  mysql:
    restart: always # Автоматический перезапуск контейнера при остановке.
    image: mysql # Используем официальный образ MySQL для создания контейнера базы данных.
    environment:
      - MYSQL_ROOT_PASSWORD=password # Устанавливаем пароль для пользователя root.
      - MYSQL_DATABASE=time_db # Указываем имя создаваемой базы данных.
    volumes:
      - mysql_data:/var/lib/mysql # Подключение тома для постоянного хранения данных MySQL.

  # Определение сервиса Adminer - веб-интерфейса для управления MySQL.
  adminer:
    restart: always # Автоматический перезапуск контейнера при остановке.
    image: adminer # Используем образ Adminer для быстрого развертывания интерфейса управления базой данных.
    ports:
      - "8888:8080" # Порт 8888 на хосте будет сопоставлен с портом 8080 внутри контейнера.

# Определение тома для хранения данных MySQL.
volumes:
  mysql_data:
